apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lighthousejobs.lighthouse.jenkins.io
spec:
  group: lighthouse.jenkins.io
  names:
    kind: LighthouseJob
    singular: lighthousejob
    plural: lighthousejobs
    shortNames:
      - lhjob
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
