apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Chart.Name }}"
  name: {{ .Chart.Name }}
{{- if .Values.Annotations }}
  annotations:
{{ toYaml .Values.Annotations | indent 4 }}
{{- end }}
spec:
  # backoffLimit: {{ .Values.BackoffLimit }}
  template:
    metadata:
      name: "{{.Release.Name}}"
      # istio-proxy prevents job pods from completing if istio is enabled
      # https://github.com/istio/istio/issues/6324
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.Image }}:{{ .Values.ImageTag }}"
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi
        name: {{ .Chart.Name }}
        command: ["/exposecontroller"]
        args: 
{{- range .Values.Args }}
        - {{ . | quote }}
{{- end }}
      serviceAccountName: {{ .Chart.Name }}
      restartPolicy: Never
