{{- if not .Values.proxysql.cluster.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
    {{ include "proxysql.labels" . | nindent 4 }}
{{ if .Values.annotations| default false }}
  annotations:
{{ with .Values.annotations }}
    {{- tpl (toYaml .) $ | indent 4 }}
{{ end }}
{{ end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "proxysql.selectorLabels" . | nindent 6 }}
  template:
    {{- include "proxysql.pod" . | nindent 4 }}
{{- end }}
