dependencies:
  - name: kube-state-metrics
    version: "2.12.2"
    repository: https://kubernetes.github.io/kube-state-metrics
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "1.18.2"
    repository: https://rafaelcalleja.github.io/helm-charts/
    condition: nodeExporter.enabled
  - name: grafana
    version: "6.4.2"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
