apiVersion: v1
kind: Secret
metadata:
  name: {{ include "g4f.fullname" . }}
  labels:
{{ include "g4f.labels" . | indent 4 }}
type: Opaque
data:
{{- (.Files.Glob "secrets/*").AsSecrets | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "g4f.fullname" . }}-env
  labels:
{{ include "g4f.labels" . | indent 4 }}
type: Opaque
stringData:
{{- range $pkey, $pval := .Values.env }}
  {{ $pkey }}: {{ $pval|quote }}
{{- end }}
