{{- if or .Values.prow.enabled .Values.lighthouse.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hook
  annotations:
    kubernetes.io/ingress.class: {{ .Values.hook.ingress.class }}
{{- if .Values.cluster.ingress.annotations }}
{{ toYaml .Values.cluster.ingress.annotations | indent 4 }}
{{- end }}
{{- if .Values.hook.ingress.annotations }}
{{ toYaml .Values.hook.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: hook{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    http:
      paths:
      - backend:
          service:
            name: hook
            port:
              number: 80
        pathType: ImplementationSpecific
{{- if .Values.cluster.tls }}
  tls:
  - hosts:
    - hook{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
{{- if .Values.hook.ingress.tls.secretName }}
    secretName: "{{ .Values.hook.ingress.tls.secretName }}"
{{- else if .Values.cluster.ingress.tls.secretName }}
    secretName: "{{ .Values.cluster.ingress.tls.secretName }}"
{{- else if eq .Values.certmanager.production "true" }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
