{{- if .Values.CoreChartmuseum }}
apiVersion: v1
data:
  BASIC_AUTH_PASS: {{ .Values.CoreChartmuseum.password | b64enc | quote }}
  BASIC_AUTH_USER: {{ .Values.CoreChartmuseum.username | b64enc | quote }}
kind: Secret
metadata:
  annotations:
    jenkins.io/credentials-keybinding-password: BASIC_AUTH_PASS
    jenkins.io/credentials-keybinding-username: BASIC_AUTH_USER
    jenkins.io/foo: bar
  labels:
    jenkins.io/credentials-type: usernamePassword
    release: jenkins-x
  name: jenkins-x-chartmuseum-core
type: Opaque
{{- end }}