{{- if  and .Values.gitops.dev.repo .Values.gitops.dev.owner }}
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  name: "{{ .Values.gitops.dev.owner | default .Values.gitops.owner | lower }}-{{ .Values.gitops.dev.repo }}"
  labels:
    jenkins.io/gitSync: "false"
spec:
  provider: "{{ .Values.gitops.dev.server | default .Values.gitops.server }}"
  providerName: '{{ .Values.gitops.gitName | default .Values.gitops.gitKind | default "github" }}'
  providerKind: '{{ .Values.gitops.gitKind | default "github" }}'
  org: "{{ .Values.gitops.dev.owner | default .Values.gitops.owner }}"
  repo: "{{ .Values.gitops.dev.repo }}"
  url: "{{ .Values.gitops.dev.server | default .Values.gitops.server }}{{ .Values.gitops.gitUrlPathPrefix}}/{{ .Values.gitops.dev.owner | default .Values.gitops.owner }}/{{ .Values.gitops.dev.repo }}.git"
  httpCloneURL: "{{ .Values.gitops.dev.server | default .Values.gitops.server }}{{ .Values.gitops.gitUrlPathPrefix}}/{{ .Values.gitops.dev.owner | default .Values.gitops.owner }}/{{ .Values.gitops.dev.repo }}.git"
  description: "the git repository for the Dev environment - used to manage the Jenkins X installation"
  scheduler:
    kind: Scheduler
    name: "{{ .Values.gitops.dev.scheduler }}"
{{- end }}
