apiVersion: v1
data:
  domain: {{ .Values.cluster.domain }}
  email: ""
  exposer: {{ .Values.cluster.exposer }}
  issuer: ""
  tls: {{ .Values.cluster.tls | quote }}
kind: ConfigMap
metadata:
  name: ingress-config
