{
 "title": "Cluster",
 "tags": [
  "jenkins-x",
  "kubernetes"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\",status=\"true\",job=\"kube-state-metrics\"})",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "pods" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[5m]))",
     "legendFormat": "cpu_seconds"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)-sum(node_memory_MemFree_bytes)",
     "legendFormat": "used"
    },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "free" }
   ]
  }
 ]
}