{
 "title": "Tekton",
 "tags": [
  "jenkins-x",
  "tekton"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "controller", "query": "pipelinerun,taskrun" },
   {
    "name": "level",
    "query": "error, warning, info, debug, trace"
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "PipelineRun Reconciliations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (rate(tekton_pipelines_controller_reconcile_count{reconciler=\"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler\"}[5m]))"
    }
   ]
  },
  {
   "title": "TaskRun Reconciliations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (rate(tekton_pipelines_controller_reconcile_count{reconciler=\"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler\"}[5m]))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_processes{namespace=\"tekton-pipelines\"}) by (pod)",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Pipelines by status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(tekton_pipelines_controller_pipelinerun_count[5m]))"
    }
   ]
  },
  {
   "title": "Running Pipelines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tekton_pipelines_controller_running_pipelineruns_count)",
     "legendFormat": "running pipelines"
    }
   ]
  },
  {
   "title": "Logs by controller",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"tekton-pipelines/controller\"} |~ \"(?i)$search\"|~ \"(?i)$level\" | json | line_format \"{{.log}}\" | json| __error__!=\"\" | label_format controller=\"{{TrimSuffix (TrimPrefix .knative_dev_controller `github.com.tektoncd.pipeline.pkg.reconciler.`) `.Reconciler`}}\" [$__interval])) by (knative_dev_controller)"
    }
   ]
  },
  {
   "title": "Logs by level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"tekton-pipelines/controller\"} |~ \"(?i)$search\" |~ \"$controller\" |~ \"(?i)$level\"| json | line_format \"{{.log}}\" [$__interval])) by (level)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{job=\"tekton-pipelines/controller\"} |~ \"(?i)$search\" |~ \"(?i)$level\" |~ \"$controller\" | json | line_format \"{{.log}}\" | json | label_format controller=\"{{TrimSuffix (TrimPrefix .knative_dev_controller `github.com.tektoncd.pipeline.pkg.reconciler.`) `.Reconciler`}}\" | line_format \"{{.level | upper | trunc 4}}\\t[{{if eq .logger `tekton-pipelines-controller.event-broadcaster`}}event{{else}}{{.controller}}{{end}}]\\t{{with .knative_dev_key}}{{.}}: {{end}}{{.msg}}\""
    }
   ]
  }
 ]
}